(() => {
'use strict';
const bank=window.QUIZ_BANK, main=document.getElementById('main');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const requested=new URLSearchParams(location.search).get('c'),chapter=bank.chapters.find(c=>String(c.id)===requested);
let storage=true;
function read(c){try{const d=JSON.parse(localStorage.getItem(`${bank.version}-${c.id}`)||'null');if(d&&Array.isArray(d.answers)&&d.answers.length===c.questions.length&&d.answers.every(a=>a===null||Number.isInteger(a)&&a>=0&&a<4)&&Number.isInteger(d.current)&&d.current>=0&&d.current<c.questions.length&&(!d.submitted||d.answers.every(a=>a!==null)))return {answers:d.answers,current:d.current,submitted:d.submitted===true};}catch(e){storage=false;}return {answers:c.questions.map(()=>null),current:0,submitted:false};}
function write(){try{localStorage.setItem(`${bank.version}-${chapter.id}`,JSON.stringify(state));}catch(e){storage=false;}}
function focus(){main.focus({preventScroll:true});window.scrollTo(0,0);}
function source(q){return q.sources.map(s=>`<a target="_blank" rel="noopener" href="${bank.lectureUrl}#${encodeURIComponent(s.id)}">Slide ${s.slide} · click ${s.click}</a>`).join('');}
function home(){main.innerHTML=`<p class="eyebrow">Biologia · Ciclo cellulare e riproduzione</p><h1>Fermati. Prova a spiegartelo.</h1><p class="intro">Quattro domande alla fine di ogni capitolo, senza cronometro. Prima rispondi, poi confronta il tuo ragionamento con la spiegazione.</p>${requested&&!chapter?'<p class="notice">Questo capitolo non esiste. Scegli uno dei capitoli qui sotto.</p>':''}<div class="grid">${bank.chapters.map(c=>{const d=read(c),score=d.answers.filter((a,i)=>a===c.questions[i].correct).length;return `<article class="chapter"><div class="idx">${String(c.id).padStart(2,'0')} / SLIDE ${c.start}–${c.end}</div><h2>${esc(c.title)}</h2><p>${esc(c.goal)}</p><p class="meta">4 domande · circa 3–5 minuti${d.submitted?` · ultimo risultato ${score}/4`:''}</p><a class="btn small" href="?c=${c.id}">${d.submitted?'Rivedi il risultato':d.answers.some(a=>a!==null)?'Riprendi':'Inizia il quiz'} <span aria-hidden="true">→</span></a></article>`;}).join('')}</div>`;}
if(!chapter){home();return;}
document.title=chapter.title+' · Quiz AGtest';let state=read(chapter);
function intro(){main.innerHTML=`<div class="quiz"><p class="eyebrow">Capitolo ${chapter.id} · slide ${chapter.start}–${chapter.end}</p><h1>${esc(chapter.title)}</h1><p class="intro">${esc(chapter.goal)}</p><div class="notice"><strong>4 domande, una risposta per domanda.</strong><br>Puoi tornare indietro e cambiare idea. Le soluzioni compaiono soltanto dopo la consegna, con il motivo e il riferimento alla lezione.</div><p>Usa quello che hai appena visto: non servono gli argomenti dei capitoli successivi.</p><div class="actions"><button class="btn" id="start">${state.answers.some(a=>a!==null)?'Riprendi il quiz':'Comincia'}</button></div><p class="hint">Le risposte vengono conservate solo in questo browser e non inviate al docente.</p></div>`;document.getElementById('start').onclick=()=>{render();focus();};}
function render(){if(state.submitted){result();return;}const i=state.current,q=chapter.questions[i];main.innerHTML=`<div class="quiz"><p class="eyebrow">Capitolo ${chapter.id} · ${esc(chapter.title)}</p><p class="meta">Domanda ${i+1} di ${chapter.questions.length}</p><div class="progress" aria-hidden="true"><div style="width:${(i+1)/chapter.questions.length*100}%"></div></div><form class="question"><fieldset><legend>${esc(q.prompt)}</legend><div class="options">${q.options.map((s,j)=>`<label class="option"><input type="radio" name="answer" value="${j}" ${state.answers[i]===j?'checked':''}><span>${esc(s)}</span></label>`).join('')}</div></fieldset><div class="actions"><button class="btn alt" type="button" id="back" ${i===0?'disabled':''}>Indietro</button><button class="btn" id="next" type="submit" ${state.answers[i]===null?'disabled':''}>${i===chapter.questions.length-1?'Consegna e correggi':'Prossima domanda'}</button></div><p class="hint">${storage?'Puoi modificare le risposte prima della consegna.':'Il browser non consente il salvataggio: completa il quiz senza chiudere la pagina.'}</p></form></div>`;
main.querySelectorAll('input').forEach(input=>input.onchange=()=>{state.answers[i]=Number(input.value);write();document.getElementById('next').disabled=false;});document.getElementById('back').onclick=()=>{if(i>0){state.current--;write();render();focus();}};main.querySelector('form').onsubmit=e=>{e.preventDefault();if(state.answers[i]===null)return;if(i<chapter.questions.length-1){state.current++;}else if(state.answers.every(a=>a!==null)){state.submitted=true;}else{state.current=state.answers.indexOf(null);}write();render();focus();};}
function result(){const n=state.answers.filter((a,i)=>a===chapter.questions[i].correct).length;main.innerHTML=`<div class="quiz"><p class="eyebrow">Capitolo ${chapter.id} · correzione</p><h1>${n===4?'Il ragionamento regge.':'Ripartiamo dai passaggi da chiarire.'}</h1><div class="score"><strong>${n} / 4</strong><p>Risposte corrette.<br>${n===4?'Prova ora a spiegare una risposta con parole tue.':'Leggi perché, poi torna al passaggio della lezione se serve.'}</p></div>${chapter.questions.map((q,i)=>{const ok=state.answers[i]===q.correct;return `<article class="review"><span class="tag ${ok?'':'wrong'}">${ok?'Corretta':'Da rivedere'} · domanda ${i+1}</span><h3>${esc(q.prompt)}</h3><p>La tua risposta: ${esc(q.options[state.answers[i]])}</p>${ok?'':`<p class="answer">Risposta corretta: ${esc(q.options[q.correct])}</p>`}<p>${esc(q.explanation)}</p><div class="sources">Ritrova il passaggio: ${source(q)}</div></article>`;}).join('')}<div class="actions"><button class="btn" id="retry">Riprova il capitolo</button><button class="btn alt" id="download">Scarica il risultato</button><a href="./">Tutti i capitoli</a></div><p class="hint">Questo risultato è personale e non viene inviato al docente.</p></div>`;
document.getElementById('retry').onclick=()=>{state={answers:chapter.questions.map(()=>null),current:0,submitted:false};write();render();focus();};document.getElementById('download').onclick=()=>{const txt=`AGtest — ${chapter.title}\nRisultato: ${n}/4\n\n`+chapter.questions.map((q,i)=>`${i+1}. ${q.prompt}\nRisposta: ${q.options[state.answers[i]]}\nEsito: ${state.answers[i]===q.correct?'corretta':'da rivedere'}\nSpiegazione: ${q.explanation}\nRiferimenti: ${q.sources.map(s=>`slide ${s.slide}, click ${s.click}`).join('; ')}\n`).join('\n');const url=URL.createObjectURL(new Blob([txt],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`AGtest-capitolo-${chapter.id}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};}
if(state.submitted)result();else intro();
})();
