(() => {
'use strict';
const API='https://agtest-classe.ludoquercia.chatgpt.site/api/live',main=document.getElementById('main'),room=new URLSearchParams(location.search).get('room');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let token,state=null,busy=false,lastKey='',deadline=0,offset=0,choice=null;
if(!room){main.innerHTML='<div class="quiz"><p class="eyebrow">AGtest · In classe</p><h1>Entriamo tutti. Poi si parte.</h1><p class="intro">Inquadra il QR che il docente mostra alla fine del capitolo e premi «Entra nella sessione».</p><div class="notice">Le domande partono quando il docente preme <strong>Start</strong>. Hai <strong>45 secondi per ogni domanda</strong>, uguali per tutta la classe. Tocca una risposta per registrarla; puoi cambiarla fino allo scadere del tempo.</div><p>Alla fine vedrai il tuo risultato nella tua area personale e le spiegazioni delle risposte sbagliate o non date. La distribuzione dei punteggi della classe apparirà sulla presentazione.</p></div>';return;}
try{token=localStorage.getItem('agtest-live:'+room);if(!token){token=crypto.randomUUID()+crypto.randomUUID();localStorage.setItem('agtest-live:'+room,token);}}catch(e){main.innerHTML='<p class="notice">Per mantenere la tua iscrizione, abilita il salvataggio del browser e riapri questo QR.</p>';return;}
main.innerHTML='<div class="quiz"><p class="eyebrow">AGtest · In classe</p><h1>Pronto a partecipare?</h1><p>45 secondi per domanda. Non serve un account né il tuo nome.</p><button class="btn" id="join">Entra nella sessione</button><p id="connection" role="status"></p></div>';
const msg=text=>{let p=document.getElementById('connection');if(!p){p=document.createElement('p');p.id='connection';p.setAttribute('role','status');p.className='notice';main.prepend(p);}p.textContent=text;p.hidden=!text;};
async function request(action,extra={}){const start=Date.now();const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,room,token,...extra}),signal:AbortSignal.timeout(10000)}),d=await r.json();if(!r.ok)throw Error(d.error||'Connessione non riuscita.');if(d.serverNow)offset=d.serverNow-(start+Date.now())/2;return d;}
function render(d){state=d;deadline=d.deadline||d.startedAt||0;const key=d.status+':'+d.index;
 if(!d.joined){return;}
 if(key!==lastKey){lastKey=key;
  if(d.status==='waiting'||d.status==='countdown')main.innerHTML=`<div class="quiz"><p class="eyebrow">Capitolo ${d.chapter}</p><h1>${esc(d.title)}</h1><div class="notice"><strong>Sei iscritto.</strong> Aspetta lo Start del docente.<p id="waiting-count"></p><strong id="timer"></strong></div><p>${d.total} domande · ${d.period/1000} secondi ciascuna. Mantieni questa pagina aperta.</p></div>`;
  if(d.status==='running'){choice=d.choice;main.innerHTML=`<div class="quiz"><p class="eyebrow">${esc(d.title)}</p><div class="live-top"><span>Domanda ${d.index+1} di ${d.total}</span><strong id="timer" aria-label="Secondi rimasti"></strong></div><div class="progress"><div id="timebar"></div></div><form class="question"><fieldset><legend>${esc(d.question.prompt)}</legend><div class="options">${d.question.options.map((s,j)=>`<label class="option"><input type="radio" name="answer" value="${j}" ${d.choice===j?'checked':''}><span>${esc(s)}</span></label>`).join('')}</div></fieldset><p id="saved" role="status" class="hint">Tocca una risposta per registrarla.</p></form></div>`;main.querySelector('form').onsubmit=e=>e.preventDefault();main.querySelectorAll('input').forEach(i=>i.onchange=()=>submit(Number(i.value),d.question.id));main.focus({preventScroll:true});}
  if(d.status==='ended'){main.innerHTML=`<div class="quiz"><p class="eyebrow">La tua area personale · Quiz concluso</p><h1>Il tuo risultato</h1><div class="score"><strong>${d.score} / ${d.total}</strong><p>Risposte corrette.<br>Le correzioni qui sotto riguardano le tue risposte.</p></div>${d.review.map((q,i)=>`<article class="review"><span class="tag ${q.choice===q.correct?'':'wrong'}">${q.choice===null?'Non risposta':q.choice===q.correct?'Corretta':'Da rivedere'} · ${i+1}</span><h3>${esc(q.prompt)}</h3><p>La tua risposta: ${q.choice===null?'nessuna entro il tempo':esc(q.options[q.choice])}</p>${q.choice!==q.correct?`<p><strong>Risposta corretta: ${esc(q.options[q.correct])}</strong></p><p>${esc(q.explanation)}</p>`:''}</article>`).join('')}<p class="hint">Puoi ritrovare il risultato riaprendo lo stesso QR su questo browser, entro 24 ore dalla creazione della sessione.</p></div>`;}
 }
 if(d.status==='waiting'){document.getElementById('waiting-count').textContent=d.participants+' persone iscritte';}
 tick();
}
async function submit(value,question){if(busy)return;busy=true;main.querySelectorAll('input').forEach(i=>i.disabled=true);document.getElementById('saved').textContent='Registrazione…';try{const d=await request('answer',{question,choice:value});render(d);if(d.status==='running'&&d.question.id===question){choice=d.choice;document.getElementById('saved').textContent='Risposta registrata. Puoi cambiarla entro il tempo.';}msg('');}catch(e){msg(e.message+' Controlla la connessione.');main.querySelectorAll('input').forEach(i=>i.checked=Number(i.value)===choice);}finally{busy=false;tick();}}
function tick(){if(!state)return;const seconds=Math.max(0,Math.ceil((deadline-Date.now()-offset)/1000));const t=document.getElementById('timer');if(t)t.textContent=state.status==='countdown'?'Partenza tra '+seconds+'…':state.status==='running'?seconds+' s':'';const bar=document.getElementById('timebar');if(bar)bar.style.width=(seconds/(state.period/1000)*100)+'%';main.querySelectorAll('input').forEach(i=>i.disabled=busy||seconds<=0);}
let polling=false;async function poll(){if(polling||busy||state?.status==='ended')return;polling=true;try{const d=await request('state');if(d.joined){render(d);msg('');}}catch(e){msg('Connessione interrotta. Il tempo di classe continua: provo a riconnettermi.');}finally{polling=false;}}
document.getElementById('join').onclick=async()=>{const b=document.getElementById('join');b.disabled=true;try{render(await request('join'));msg('');}catch(e){msg(e.message);b.disabled=false;}};
setInterval(poll,1000);setInterval(tick,100);document.addEventListener('visibilitychange',()=>{if(!document.hidden)poll();});poll();
})();
